workflow: ""
singularity_image: ""
sample_file: "config/samples_info.tab"
genome: ""
spike_genome: ""
GTF: ""
TE_GTF: ""
chromosome_lengths: ""
effective_genome_size: ""
prepDE_length: ""
stringtie_strandedness: "--rf"
featurecounts_strandedness: 2
TE_strandedness: "reverse"