workflow: "ATACseq_PE"
sample_file: "config/samples_info.tab"
genome: "/gpfs/data/cvrcbioinfolab/gildem01/genomes/mm10/bowtie2/mm10_index"
spike_genome: ""
GTF: ""
chromosome_lengths: ""
effective_genome_size: "2652783500"
prepDE_length: ""
